add fields(code / isActive / mobile) to user model
farshid0594/taskmanager-backend pull request #3
Opened 2021-12-22 19:32 UTC by MohammadKoolivand

i add some fields to user model for signup route

2021-12-22 19:53 UTC, farshid0594 commented on src/models/User.js
> +        username: { type: String, required: true },
add unique=true to unique fields

2021-12-22 19:54 UTC, farshid0594 commented on src/models/User.js
>          name: String,
set max length to name field

2021-12-22 19:55 UTC, farshid0594 commented on src/models/User.js
> +        code: { codeNo: Number, expired: String },
change codeNo to text .

2021-12-22 19:56 UTC, farshid0594 commented on src/models/User.js
> +        mobile: { type: String, required: true },
add index=true to fields need to index.

2021-12-22 19:59 UTC, farshid0594 requested changes
review comments

2021-12-22 22:04 UTC, MohammadKoolivand commented on src/models/User.js
> +        username: { type: String, required: true },
added to username and mobile

2021-12-22 22:06 UTC, MohammadKoolivand commented on src/models/User.js
> +        mobile: { type: String, required: true },
added index to username

2021-12-22 22:38 UTC, farshid0594 approved these changes

2021-12-23 10:23 UTC, amirhnr approved these changes

2021-12-23 10:27 UTC, merged