change model
farshid0594/taskmanager-backend pull request #5
Opened 2021-12-23 19:23 UTC by MohammadKoolivand

User model has been changed for new signup strategy

2021-12-23 19:29 UTC, amirhnr approved these changes

2021-12-23 21:01 UTC, amirhnr approved these changes

2021-12-23 21:17 UTC, alikia1995 approved these changes
dear Mohammad.
tanks for your hard work. I verify your code

2021-12-23 23:08 UTC, farshid0594 commented on src/models/User.js
>      mobile: { type: String, required: true, unique: true },
add index:true to mobile

2021-12-23 23:10 UTC, farshid0594 requested changes
add index to mobile field

2021-12-24 08:02 UTC, mehdigadyari approved these changes

2021-12-24 08:57 UTC, alikia1995 approved these changes

2021-12-24 09:04 UTC, alikia1995 approved these changes

2021-12-24 10:24 UTC, MohammadKoolivand commented on src/models/User.js
>      mobile: { type: String, required: true, unique: true },
done

2021-12-24 10:34 UTC, farshid0594 approved these changes

2021-12-24 10:35 UTC, merged